//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDS_FIRSTCOLUMN                 1
#define IDS_SECONDCOLUMN                2
#define IDS_THIRDCOLUMN                 3
#define IDCANCEL2                       3
#define IDS_4COLUMN                     4
#define IDS_APP_TITLE                   5
#define IDS_5COLUMN2                    5
#define IDS_5COLUMN                     6
#define IDS_APP_TITLE1                  6
#define IDS_CDRDAO                      7
#define IDS_CDRECORD                    8
#define IDS_MKISOFS                     9
#define IDS_STGERASECD                  10
#define IDS_STGCHGCD                    11
#define IDS_STGCONTINUE                 12
#define IDS_STGPBGRAVE                  13
#define IDS_STGISOCREATION              14
#define IDS_STGENDTHE                   15
#define IDS_STGINITBURNING              16
#define IDS_STGBURNBEGIN                17
#define IDS_STGENDBURN                  18
#define IDS_STGBURNON                   19
#define IDS_STGSECONDES                 20
#define IDS_STGOPENRAWFILE              21
#define IDS_STGORGCOLOR                 22
#define IDS_STGVNGINTERPOL              23
#define IDS_STGCONVERTRGB               24
#define IDS_STGBITMAPCREATION           25
#define IDS_STGIMPORTIMAGE              26
#define IDS_STGSUPFILE                  27
#define IDS_STGSELECTBURNER             28
#define IDS_STGSELBURN                  29
#define IDS_STGCDNORW                   30
#define IDS_STGHEADINFOFILE             31
#define IDS_STGAFFINFOFILE              32
#define IDS_STGNOMFICHIER               33
#define IDS_STGDATECREATION             34
#define IDS_STGDATEMODIFICATION         35
#define IDS_STGFORMATIMAGE              36
#define IDS_STGLARGEUR                  37
#define IDS_STGHAUTEUR                  38
#define IDS_STGTAILLE                   39
#define IDS_STGKEYWORD                  40
#define IDS_STGFORMINFOFILE             41
#define IDS_STGTABLEINFOFILE            42
#define IDS_STGAFFKEYWORD               43
#define IDS_STGENDINFOFILE              44
#define IDS_STGMEMORYERROR              45
#define IDS_STGINITENCOURS              46
#define IDS_STGCREATIONFENETRE          47
#define IDS_STGCREATIONMENU             48
#define IDS_SGINITPARAM                 49
#define IDS_STGTOTALFICHIER             50
#define IDS_STRING51                    51
#define IDS_STGTOTALFICHIERFREE         51
#define IDS_STGINFOSDOWNLOAD            52
#define IDM_REGARDS                     101
#define IDM_ABOUT                       104
#define IDC_PTPLUS                      104
#define ID_TOOLBAR                      105
#define IDC_NODROP                      106
#define IDI_AFFICHAGEBITMAP             107
#define IDM_AFFICHAGEBITMAP             108
#define IDI_SMALL                       110
#define IDC_AFFICHAGEBITMAP             112
#define IDC_TRTBITMAP                   113
#define IDC_CURSOR1                     114
#define IDS_TITLE_TRTBITMAP             114
#define IDD_ABOUTBOX                    115
#define IDS_ICONELARGE                  115
#define IDD_BRIGHTCONT                  116
#define IDS_ICONEPETITE                 116
#define IDD_JPGSAVE                     117
#define IDS_ICONELIST                   117
#define IDD_REDIMIMAGE                  118
#define IDS_ICONEDETAIL                 118
#define IDR_REGARDS                     119
#define IDS_ICONEMINI                   119
#define IDD_SLIDESHOW                   120
#define IDS_REPERTOIRESUP               120
#define IDM_TRAITEMENTIMAGE             121
#define IDS_AFFICHAGEIMAGE              121
#define IDS_TRAITEMENTIMAGE             122
#define IDR_TRTBITMAP                   123
#define IDS_IMGSUIVANTE                 123
#define IDR_TOOLBAR1                    124
#define IDS_IMGPRECEDENTE               124
#define IDS_IMGPREMIER                  125
#define IDS_IMGDERNIER                  126
#define IDS_REVERT                      127
#define IDS_PLEINECRAN                  128
#define IDS_ROTATE90CW                  129
#define IDS_ROTATE90CCW                 130
#define IDS_FLIPVERT                    131
#define IDS_FLIPHORZ                    132
#define IDS_AFFICHAGEDOSSIER            133
#define IDB_FOLDER                      134
#define IDS_AFFICHAGERECHERCHE          134
#define IDS_WIZARD                      135
#define IDS_TITREWIZARD                 136
#define IDM_CATALOGUE                   137
#define IDS_LIBELLEWIZARD               137
#define IDS_MENUGESTIONALBUM            138
#define IDS_ASSOCIATION                 139
#define IDS_INFOS                       140
#define IDS_ZIPAJOUT                    141
#define IDM_MENULISTE                   142
#define IDS_ZIPSUP                      142
#define IDS_ZIPEXTRAIRE                 143
#define IDB_ALBUM                       144
#define IDS_ZIPVOIR                     144
#define IDM_ALBUM                       145
#define IDS_ZIPSELECTALL                145
#define IDD_NEWALBUM                    146
#define IDS_ALBUMNAME                   146
#define IDD_GSTCATEGORIE                147
#define IDS_SUPPALBUM                   147
#define IDD_FICHIER                     148
#define IDS_ALBUMEXISTANT               148
#define IDD_ATTRIBUTIMAGE               149
#define IDS_ALBUMCRITERE                149
#define IDD_SELECTALBUM                 150
#define IDS_ALBUMIMAGECRITERE           150
#define IDS_SUPPIMAGE                   151
#define IDS_SUPPFILE                    152
#define IDS_ERRORIMPRIMANTE             153
#define IDD_MENUWIZARD                  154
#define IDS_ERRORFICHIER                154
#define IDB_ALBUMWIZARD                 155
#define IDS_ERREUR                      155
#define IDB_PROPWIZARD                  156
#define IDS_ERRORVIDEO                  156
#define IDB_RECHERCHEWIZARD             157
#define IDS_MODIFREDEMARRAGE            157
#define IDS_HELPFILENAME                158
#define IDS_SUPPONEFILE                 159
#define IDS_MENUPHOTONUMERIQUE          160
#define IDD_MENUALBUM                   161
#define IDS_RENSFORM                    161
#define IDD_GSTALBUM                    162
#define IDS_VERSION                     162
#define IDD_AJOUTCRITEREALBUM           163
#define IDS_AUTEUR                      163
#define IDD_FIN                         164
#define IDS_COPYRIGHT                   164
#define IDS_CANCEL                      165
#define IDD_SELECTALBUMWIZARD           166
#define IDS_ZIPFILE                     166
#define IDS_COMPRESSSIZE                167
#define IDS_MODIFYTHE                   168
#define IDB_PLUS                        169
#define IDS_PATH                        169
#define IDB_MOINS                       170
#define IDS_FILE                        170
#define IDS_CATEGORYVALEUR              171
#define IDS_CATEGORYNUMERO              172
#define IDC_PTMOINS                     173
#define IDS_CATEGORYATTRIBUT            173
#define IDD_CATALOGUEMENU               174
#define IDS_ATTRIBUTPICTUREREP          174
#define IDS_NEWCRITERE                  175
#define IDS_CATEGORYLIBELLE             176
#define IDB_BANNER256                   177
#define IDS_HANDTOOLS                   177
#define IDS_CROPTOOLS                   178
#define IDB_WATERMARK256                179
#define IDS_ZOOMTOOLS                   179
#define IDS_CDRWARNING                  180
#define IDS_GRAVUREMENU                 181
#define IDS_GRAVUREINIT                 182
#define IDS_SELECTIONALBUM              183
#define IDS_DRIVENOTAVAILABLE           184
#define IDS_PICTUREFORMAT               185
#define IDS_IMPNONDISPO                 186
#define IDS_SUPPCATALOGUE               187
#define IDS_FICHIERNONTROUVE            188
#define IDS_UPDATECATALOGUE             189
#define IDB_MAINHOT                     190
#define IDS_COMPACTCATALOGUE            190
#define IDB_MENUBMP                     191
#define IDS_CATALOGUENAME               191
#define IDS_CRITERELIST                 192
#define IDD_MP3PLAYER                   193
#define IDS_CRITERECATALOGUE            193
#define IDS_CRITEREPRESENT              194
#define IDD_ZIPDLG                      195
#define IDS_CRITEREERREUR               195
#define IDB_ICONEZIP                    196
#define IDS_WINDOWCATCREATE             196
#define IDM_MENUZIP                     197
#define IDS_ENTETEHTMLCATALGOUE         197
#define IDS_PICTUREFORMATMULTI          199
#define IDB_SELECTED                    201
#define IDB_MAIN                        203
#define IDB_MASK                        204
#define IDB_BTPLAYER                    208
#define IDD_PRINTDLGBOX                 211
#define IDD_RGB                         212
#define IDD_ASSOCIATE                   213
#define IDB_PHOTO                       214
#define IDD_SELECTPHOTO                 215
#define IDD_CONVERTRENOMMAGE            216
#define IDC_CURSELECT                   220
#define IDB_TRAITEMENTMENU              224
#define IDC_ZOOMON                      225
#define IDC_ZOOMOUT                     226
#define IDB_BORDER                      227
#define IDD_FINGRAVURE                  228
#define IDD_DEBUTGRAVURE                229
#define IDD_GRAVURE                     230
#define IDD_APPLITRAITEMENT             282
#define IDB_PICTBORDER                  284
#define IDD_DLGCOLOR                    285
#define IDD_DLGPROPIMP                  286
#define IDD_DLGLENSFLARE                287
#define IDB_CATALOGUE                   290
#define IDD_DLGCATASEARCH               291
#define IDD_DLGLISTFIND                 292
#define IDD_SELECTDIRCHECK              293
#define IDD_DLGCLOUDS                   294
#define IDI_CATALOGUE                   297
#define IDI_ALBUM                       298
#define IDD_DLGMOTIONBLUR               303
#define IDD_DLGWIENER                   304
#define IDD_DLGROTATE                   305
#define IDD_DLGCANVAS                   306
#define IDB_FONT                        308
#define IDD_INTRO                       311
#define IDB_DLGINTRO                    313
#define IDB_PICTURE                     316
#define IDD_DLGPROGRESSBAR              317
#define IDD_BURNISO                     318
#define IDD_DLGSELECTGRAVEUR            319
#define IDD_DLGISOCREATE                320
#define IDD_DIALOG1                     325
#define IDD_DLGKEYWORD                  325
#define IDR_HTML1                       327
#define IDR_HTML_EXIF                   328
#define IDD_DLGICONESIZE                329
#define IDD_CATALOGUEMENU2              331
#define IDB_FOLDERBIG                   343
#define IDD_DLGPHOTOFILTER              344
#define IDD_DLG_HISTOGRAMME             345
#define IDS_STGIMPORTPICTURE            500
#define IDS_STGRAWFILE                  501
#define IDS_PICTUREFORMATWITHOUTRAW     502
#define IDS_PICTUREFORMATMULTIWITHOUTRAW 503
#define IDS_COMPACTDATAREADY            504
#define IDS_ADRESSEWEBVERSION           505
#define IDS_ADRESSEWEB                  507
#define IDS_REGARDSVERSION              508
#define IDS_VALEURNONVALIDE             509
#define IDS_DOSSIER                     510
#define IDS_PREVIEW                     511
#define IDS_SAVEPICTURE                 512
#define IDS_VIDEOFORMAT                 513
#define IDS_MESSAGEDISKGO               514
#define IDS_MESSAGEDISKMO               515
#define IDS_MSGERRORWIENER              516
#define IDS_MSGWIENERNBFLOT             517
#define IDS_MSGREDIMSPACE               518
#define IDS_OU                          519
#define IDS_ET                          520
#define IDS_RUNSEARCHMSG1               521
#define IDS_RUNSEARCHMSG2               522
#define IDS_RUNSEARCHMSG3               523
#define IDS_RUNSEARCHMSG4               524
#define IDS_RUNSEARCHMSG5               525
#define IDS_SADEARMSG1                  526
#define IDS_SADEARMSG2                  527
#define IDS_INSERTALBUMMSG1             528
#define IDS_INSERTALBUMMSG2             529
#define IDS_INSERTALBUMMSG3             530
#define IDS_INSERTALBUMMSG4             531
#define IDS_SELECTDIR                   533
#define IDS_MINIATURELIST               534
#define IDS_MODTRAITEMENT               535
#define IDC_BUTTON1                     1000
#define IDC_SLIDERDELAI                 1000
#define IDC_PRGBAR                      1000
#define IDC_LARGEUR                     1001
#define IDC_EDITDELAI                   1001
#define IDC_HAUTEUR                     1002
#define IDC_SEQRADAVANT                 1002
#define IDC_SLIDERBRIGHTNESS            1003
#define IDC_SEQRADARRIERRE              1003
#define IDC_SLIDERCONTRAST              1004
#define IDC_EDCONTRAST                  1005
#define IDC_BTSTART                     1005
#define IDC_EDBRIGHTNESS                1006
#define IDC_STDELAI                     1006
#define IDC_CHECKPREV                   1007
#define IDC_CHECKSHRINK                 1007
#define IDC_SLIDERQUALITY               1008
#define IDC_FULLSCREEN                  1008
#define IDC_ALBUMNAME                   1009
#define IDC_EBQUALITY                   1011
#define IDC_NEW                         1013
#define IDC_DELETE                      1014
#define IDC_PRGFILE                     1016
#define IDC_FILEIN                      1017
#define IDC_FILEOUT                     1018
#define IDC_LISTATTRIBUT                1020
#define IDC_OK                          1021
#define IDC_CANCEL                      1022
#define IDC_CMBALBUM                    1026
#define IDC_RDCREER                     1028
#define IDC_RDMODIFIER                  1029
#define IDC_RDSUPPRIMER                 1030
#define IDC_LBLALBUM                    1033
#define IDC_LBLREP                      1034
#define IDC_BTREP                       1035
#define IDC_LSIMAGEDIR                  1036
#define IDC_AJOUTIMAGE                  1037
#define IDC_AJOUTTOUT                   1038
#define IDC_SUPIMAGE                    1039
#define IDC_SUPTOUT                     1040
#define IDC_LBALBUMIMAGE                1041
#define IDC_RDALBUM                     1042
#define IDC_RDRECHERCHE                 1043
#define IDC_RDATTRIBUTS                 1044
#define IDC_LISTALBUM                   1048
#define IDC_STTITRE                     1049
#define IDC_FILENAME                    1050
#define IDC_SLDDUREE                    1051
#define IDC_DUREEINFO                   1052
#define IDC_BTPLAY                      1053
#define IDC_BTSTOP                      1054
#define IDC_BTPAUSE                     1055
#define IDC_ANIMATE1                    1056
#define IDC_FILELIST                    1057
#define IDC_BTPRECEDENT                 1064
#define IDC_BTSUIVANT                   1065
#define IDC_QUALITE                     1066
#define IDC_NEWCRITERE                  1067
#define IDC_SUPCRITERE                  1069
#define IDC_SLDRED                      1070
#define IDC_SLDGREEN                    1071
#define IDC_SLDBLUE                     1072
#define IDC_CKTIFF                      1073
#define IDC_CKJPEG                      1074
#define IDC_CKGIF                       1075
#define IDC_CKPNG                       1076
#define IDC_CKPCX                       1077
#define IDC_CKTGA                       1078
#define IDC_CKPCD                       1079
#define IDC_CKBMP                       1080
#define IDC_RDPHOTO                     1081
#define IDC_REPSTOCK                    1082
#define IDC_LBLIMAGE                    1083
#define IDC_CBINCREMENT                 1084
#define IDC_CBFORMAT                    1085
#define IDC_CMDSTOCKAGE                 1086
#define IDC_BTRECUPPHOTO                1087
#define IDC_LBLREPORIGINE               1088
#define IDC_LBLREPDESTINATION           1089
#define IDC_BTREPDEST                   1090
#define IDC_LBLLIBELLE                  1091
#define IDC_CBTAILLENUMERO              1092
#define IDC_CBINCREMEN                  1093
#define IDC_RDPOSDROITE                 1094
#define IDC_RDPOSGAUCHE                 1095
#define IDC_CHKCONVERTFORMAT            1096
#define IDC_CBLISTFORMAT                1097
#define IDC_CHKDELPHOTO                 1098
#define IDC_CHKREDIM                    1101
#define IDC_CHKRAPPORT                  1102
#define IDC_LBLHAUTEUR                  1103
#define IDC_BTREPORIGINE                1105
#define IDC_BUTTONCANCEL                1106
#define IDC_BMBEFORE                    1121
#define IDC_AFTER                       1122
#define IDC_STTEXTCOPYRIGHT             1123
#define IDC_STTEXTVERSION               1124
#define IDC_STTEXTAUTEUR                1125
#define IDC_PROGRESSBAR                 1126
#define IDC_MESSAGEBOX                  1127
#define IDC_CHECKPROPORTION             1128
#define IDC_EDPOURCENT                  1129
#define IDC_BTPRC                       1130
#define IDC_TITREGRAVURE                1131
#define IDC_INFOSGRAVURE                1132
#define IDC_SLISELECTCOLOR              1149
#define IDC_RADIO1                      1150
#define IDC_RADIO2                      1151
#define IDC_RADIO3                      1152
#define IDC_RADIO4                      1153
#define IDC_RADIO5                      1154
#define IDC_RADIO6                      1155
#define IDC_PICTMATRIX                  1156
#define IDC_RDBG                        1156
#define IDC_PICTGRADIENT                1157
#define IDC_RDBM                        1157
#define IDC_IMGTEMP                     1158
#define IDC_RDBD                        1158
#define IDC_CKJP2                       1159
#define IDC_IMGCLR2                     1159
#define IDC_CKPSD                       1160
#define IDC_RDHAUT                      1161
#define IDC_RDMIDL                      1162
#define IDC_RDBAS                       1163
#define IDC_EDHAUT                      1164
#define IDC_EDBAS                       1165
#define IDC_EDDROIT                     1166
#define IDC_EDGAUCHE                    1167
#define IDC_PCTPREV                     1168
#define IDC_FRPOS                       1169
#define IDC_FRMARGE                     1170
#define IDC_CHKROTER                    1171
#define IDC_EDITX                       1173
#define IDC_EDITY                       1174
#define IDC_EDRAYON                     1176
#define IDC_T                           1177
#define IDC_S                           1178
#define IDC_L                           1179
#define IDC_R                           1180
#define IDC_G                           1181
#define IDC_B                           1182
#define IDC_SLISELECTINTENSITE          1183
#define IDC_EDINTENSITE                 1184
#define IDC_LISTSOURCEDISPO             1185
#define IDC_SUPPCATSRC                  1186
#define IDC_SUPALLCATSRC                1187
#define IDC_LISTCOMPARAISON             1188
#define IDC_LISTCOMPARAISONDISPO        1189
#define IDC_CHECK1                      1190
#define IDC_AJOUTCATDEST                1192
#define IDC_AJOUTALLCATDEST             1193
#define IDC_SUPCATDEST                  1194
#define IDC_SUPALLCATDEST               1195
#define IDC_EDRECHERCHER                1199
#define IDC_CHKMOTSEUL                  1200
#define IDC_CHKRESPCASSE                1201
#define IDSUIVANT                       1202
#define IDC_TREEFOLDER                  1203
#define IDC_BTET                        1204
#define IDC_BTOU                        1205
#define IDC_LISTCRITERE                 1207
#define IDC_LISTSOURCE                  1208
#define IDC_IMGCLR1                     1209
#define IDC_SLIFREQUENCE                1210
#define IDC_SLIAMPLITUDE                1211
#define IDC_EDFREQUENCE                 1212
#define IDC_EDAMPLITUDE                 1213
#define IDC_AJOUTCATSRC                 1214
#define IDC_EDANGLE                     1214
#define IDC_AJOUTALLCATSRC              1215
#define IDC_EDITRECHERCHE               1216
#define IDRECHERCHE                     1217
#define IDC_BTAJOUTCRITERE              1218
#define IDC_BTPARANTHESEOUV             1220
#define IDC_BTPARANTHESEFERM            1221
#define IDC_SLANGLE                     1222
#define IDC_EDRADIUS                    1223
#define IDC_EDSIGMA                     1224
#define IDC_SLSIGMA                     1225
#define IDC_SLRADIUS                    1226
#define IDC_LSTFILTRE                   1228
#define IDC_SPFILTERH                   1229
#define IDC_SPFILTERL                   1230
#define IDC_EDRHO                       1231
#define IDC_EDFILTERL                   1232
#define IDC_EDFILTERH                   1233
#define IDC_BTPREVIEW                   1234
#define IDC_RDWIENER                    1236
#define IDC_RDCOSINUS                   1237
#define IDC_STHAUTEUR                   1239
#define IDC_STLARGEUR                   1240
#define IDC_EDHAUTEUR                   1241
#define IDC_EDLARGEUR                   1242
#define IDC_RDHG                        1243
#define IDC_RDHM                        1244
#define IDC_RDHD                        1245
#define IDC_RDMG                        1246
#define IDC_RDMM                        1247
#define IDC_RDMD                        1248
#define IDC_CK3DS                       1249
#define IDC_CKMPG                       1250
#define IDC_CKAVI                       1251
#define IDC_CHKPOURCENT                 1252
#define IDC_POURCENT                    1253
#define IDC_CBGRAVEUR                   1260
#define IDC_CKPPM                       1263
#define IDC_CKPGM                       1264
#define IDC_CKCRW                       1265
#define IDC_TXTDE                       1266
#define IDC_TXTVERS                     1267
#define IDC_PRGDATA                     1269
#define IDC_TXTTRACK                    1270
#define IDC_TXTINFOS                    1271
#define IDC_TXTDUREEESTIMEE             1272
#define IDC_TXTDUREERESTANTE            1273
#define IDC_TXTDATAINFOS                1274
#define IDC_TXTVITESSEGRAVURE           1275
#define IDC_PRGBUFFER                   1278
#define IDC_EDOUTPUT                    1281
#define IDC_STLIBELLE                   1282
#define ID_BTMODIFKEYWORD               1283
#define IDC_EDHEXA                      1284
#define IDC_SLDDENSITY                  1285
#define IDC_EDDENSITY                   1286
#define IDC_CMBFILTRE                   1287
#define IDC_RDFILTRE                    1288
#define IDC_RADIOFILTRE                 1289
#define IDC_IMGCOLOR                    1290
#define IDC_CMBNIVEAU                   1291
#define IDC_IMGHISTOGRAMME              1292
#define IDC_FRMGRADIENT                 1293
#define IDC_IMGGRADIENT                 1294
#define IDC_CHECKVISIONAGE3D            1296
#define IDC_RDTRESHAUTE                 1298
#define IDC_RDHAUTE                     1299
#define IDC_RDMOYENNE                   1300
#define IDC_RDBASSE                     1301
#define IDM_OPENFILE                    32771
#define IDM_QUITTER                     32772
#define IDM_FILTRE_NOIRETBLANC          32773
#define IDM_FILTRE_BLUR                 32774
#define IDM_IMAGES_SUIVANTE             32777
#define IDM_IMAGES_PRCDENTE             32778
#define IDM_IMAGES_ROTATEIMAGE_180      32782
#define IDM_IMAGES_ROTATEIMAGE_90CW     32783
#define IDM_IMAGES_ROTATEIMAGE_90CCW    32784
#define IDM_IMAGES_ROTATEIMAGE_FLIPHORIZONTAL 32786
#define IDM_IMAGES_ROTATEIMAGE_FLIPVERTICAL 32787
#define IDM_IMAGES_ZOOM_ZOOMIN          32788
#define IDM_IMAGES_ZOOM_ZOOMOUT         32789
#define IDM_IMAGES_VISUALISATION_DIAPORAMA 32794
#define IDM_IMAGES_VISUALISATION_PLAINECRAN 32795
#define IDM_FILTRE_SCALE                32799
#define IDM_FICHIER_SAUVERFICHIER       32800
#define IDM_FILTRE_NEGATIF              32801
#define IDM_FILTRE_BRIGHTNESSCONTRAST   32802
#define IDM_FICHIER_REVERT              32803
#define IDM_LARGEICON                   40004
#define IDM_SMALLICON                   40005
#define IDM_LISTVIEW                    40006
#define IDM_REPORTVIEW                  40007
#define IDM_NEW                         40008
#define IDM_OPEN                        40009
#define IDM_SAVE                        40010
#define IDS_CUT                         40011
#define IDS_PASTE                       40012
#define IDS_COPY                        40013
#define IDM_EXIT                        40014
#define ID_AFFICHAGE_CONTROL_TOOLBAR    40016
#define ID_AFFICHAGE_CONTROL_COMMANDEXTENSION 40017
#define ID_AFFICHAGE_CONTROL_PATHBOX    40018
#define ID_AFFICHAGE_CONTROL_STATUSBAR  40019
#define ID_AFFICHAGE_CONTROL_FOLDERTREE 40020
#define IDM_AFFICHAGE_CONTROL_PREVIEWAREA 40021
#define ID_AFFICHAGE_PREVIEW_AUTOSIZE   40022
#define ID_AFFICHAGE_PREVIEW_FULLSIZE   40023
#define IDM_THUMBMAIL                   40024
#define IDM_EDITION_SUPPRIMER           40025
#define ID_EDITION_SELECTALLFILES       40026
#define ID_EDITION_COPYTO               40027
#define ID_EDITION_MOVETO               40028
#define IDM_HELP_APROPOS                40029
#define IDM_IMAGES_SHRINKIMAGE          40030
#define ID_IMAGES_STOPDIAPORAMA         40031
#define ID_IMAGES_STARTDIAPORAMA        40032
#define IDM_EDITION_REPERTOIRESUP       40033
#define ID_FILTRE_AJOUTDEBRUIT          40034
#define ID_FILTRE_ERODE                 40035
#define ID_FILTRE_DILATE                40036
#define ID_EDITION_COLLER               40044
#define ID_EDITION_COPIER               40045
#define IDM_OUTILS_TRAITEMENTIMAGE      40046
#define IDM_AFFICHAGE_IMAGE             40047
#define ID_EDITION_ANNULER              40053
#define ID_IMAGES_VISUALISATION_PREMIREIMAGE 40054
#define ID_IMAGES_VISUALISATION_DERNIREIMAGE 40055
#define ID_EDITION_VIDAGEMEMOIRE        40056
#define ID_AFFICHAGE_AFFICHERUNIQUEMENTLESIMAGES 40057
#define ID_BUTTON40058                  40058
#define ID_OUTILS_MISEENPAPIERPEINT_ETIRER 40059
#define ID_OUTILS_MISEENPAPIERPEINT_MOSAIQUE 40060
#define ID_OUTILS_MISEENPAPIERPEINT_CENTRER 40061
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT 40065
#define ID_AFFICHAGE_ICONELARGE         40067
#define ID_AFFICHAGE_ICONEPETITE        40068
#define ID_AFFICHAGE_LISTE              40069
#define ID_AFFICHAGE_DTAILS             40070
#define ID_LISTE_AJOUTSFICHIERSDANSCATALOGUE 40071
#define ID_LISTE_SUPPRIMER              40072
#define ID_LISTE_COPIER                 40073
#define ID_LISTE_AFFICHAGEIMAGE         40074
#define ID_ALBUM_CREERUNNOUVELALBUM     40075
#define ID_CATALOGUE_NOUVELALBUM        40077
#define ID_CATALOGUE_GESTIONDESCATGORIES 40078
#define ID_AFFICHAGE_CONTROLE_RECHERCHE 40082
#define ID_LISTE_GESTIONSDESATTRIBUTS   40083
#define ID_SOUSALBUM_RENOMMER           40084
#define ID_SOUSALBUM_SUPPRIMER          40085
#define ID_ALBUM_SUPPRIMER              40086
#define ID_ALBUM_AFFICHAGEDELIMAGE      40087
#define ID_LISTE_DPLACERVERS            40088
#define ID_OUTILS_AFFICHAGEDOSSIER      40089
#define ID_OUTILS_AFFICHAGERECHERCHE    40090
#define ID_AFFICHAGE_REGENERERLESMINIATURES 40091
#define ID_EDITION_ASSOCIERREGARDSAUXIMAGES 40092
#define ID_IMAGES_IMAGEHAUTEQUALITE     40093
#define ID_SOUSALBUM_AJUSTERCRITREALBUM 40094
#define ID_AIDE_AIDE                    40095
#define ID_AFFICHAGE_ACTUALISER         40096
#define ID_ALBUM_COPIERVERS             40098
#define ID_ACTION_AJOUTERFICHIER        40099
#define ID_ACTION_SUPPRIMERFICHIER      40100
#define ID_ACTION_EXTRAIREFICHIER       40101
#define ID_ACTION_VOIRFICHIER           40102
#define ID_ACTION_TOUTSLECTIONNER       40103
#define ID_ACTION_QUITTER               40104
#define ID_AIDE_APROPOS                 40105
#define ID_LISTE_CRERUNRPERTOIRE        40106
#define ID_LISTE_NOUVEAU_CRERUNFICHIERZIP 40107
#define ID_LISTE_COMPRESSERENZIP        40108
#define ID_LISTE_DCOMPRESSERICI         40109
#define ID_LISTE_DCOMPRESSERVERS        40110
#define ID_FICHIER_TRAITEMENTIMAGE      40111
#define ID_FICHIER_EXPLORATEURIMAGE     40112
#define ID_FICHIER_IMPRIMER             40113
#define ID_FICHIER_APERUAVANTIMPRESSION 40114
#define ID_FICHIER_NOUVEAU              40116
#define ID_EDITION_SUPPRIMER            40118
#define ID_CATALOGUE_SELECTIONDUNALBUM  40119
#define ID_FILTRES_LENSFLARE            40120
#define ID_FICHIER_SELECTIONNERSOURCE   40121
#define ID_FICHIER_ACQUISITION          40122
#define ID_OUTILS_CONVERSIONETRENOMMAGEDEFICHIERS 40124
#define ID_IMAGE_AJUSTEMENT_BALANCEDESCOULEURS 40125
#define ID_FILTRES_SHARPEN              40126
#define ID_FILTRES_EMBOSS               40127
#define ID_FILTRES_EDGE                 40128
#define ID_FILTRES_SOFTEN               40129
#define ID_FILTRES_FLOUGAUSSIEN         40130
#define ID_FILTRES_MOSAQUE              40131
#define ID_IMAGE_BOUGERIMAGE            40132
#define ID_IMAGE_COUPERIMAGE            40133
#define ID_IMAGE_ZOOMERIMAGE            40134
#define ID_EDITION_MISEJOUR             40136
#define ID_SOUSALBUM_GRAVERSURCDROM     40138
#define ID_SOUSALBUM_BURNTOCDR          40139
#define ID_FICHIER_IMPRESSIONDIRECT     40140
#define ID_AFFICHAGE_CONTROLE_INFOSFICHIER 40141
#define ID_AFFICHAGE_AFFICHERLESDIMENSIONSDESIMAGES 40142
#define ID_LISTE_PASTE                  40144
#define ID_LISTE_COPY                   40145
#define ID_IMAGES_AFFICHAGEMINIATURE    40147
#define ID_IMAGE_MODE_NOIRETBLANC       40148
#define ID_FILTRES_CERCLEANTI           40149
#define ID_CATALOGUE_CRERUNCATALOGUE    40150
#define ID_SOUSCATALOGUE_SUPPRIMERCATALOGUE 40151
#define ID_SOUSCATALOGUE_METTREJOURCATALOGUE 40152
#define ID_CATALOGUE_RECHERCHER         40153
#define ID_FILTRES_NUAGES               40154
#define ID_EDITION_RECHERCHERUNFICHIER  40155
#define ID_CATALOGUE_COMPACTERLABASE    40156
#define ID_FILTRES_MEDIAN               40157
#define ID_FILTRES_FLOU_MOTIONBLUR      40159
#define ID_IMAGES_INCLURELAFFICHAGEDESSOUSRPERTOIRES 40160
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_NORMAL 40161
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BESSEL 40162
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BICUBIC 40163
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BILINEAR 40164
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BLACKMAN 40165
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BLACKMANBESSEL 40166
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BLACKMANSINC 40167
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_BOX 40168
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_CATROM 40169
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_GAUSSIAN 40170
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_HAMMING 40171
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_HANNING 40172
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_HERMITE 40173
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_LANCZOS 40174
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_MITCHELL 40175
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_QUADRATIC 40176
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_SINC 40177
#define ID_AFFICHAGE_PRVISUALISATIONENHAUTEQUALIT_TRIANGLE 40178
#define ID_IMAGE_ROTERIMAGE_ROTATIONLIBRE 40179
#define ID_FILTRES_FILTERDEWIENER       40180
#define ID_IMAGE_REDIMMENSIONNERLAFEUILLEDETRAVAIL 40181
#define ID_EDITION_SHRINKVIDEO          40184
#define ID_VIDO_DUREENCOURS             40185
#define ID_VIDO_ALLERAUBOOKMARL         40186
#define ID_LISTE_ENVOYEMEL              40191
#define ID_CATALOGUE                    40193
#define ID_FILTRES_SHARPENAVANC         40196
#define IDM_TEST_LOGGRAVURE             40197
#define ID_GRAVURE_SUPPRIMERLESFICHIERS 40199
#define ID_GRAVURE_EFFACERLECD          40200
#define ID_GRAVURE_GRAVERLESFICHIERS    40201
#define ID_IMAGE_INCLURERAW             40204
#define ID_MenuIconeBarre               40206
#define ID_MINIATURESIZE                40207
#define IDM_INFOSPICTURE                40208
#define ID_FICHIER_SAUVERALBUM          40209
#define IDM_FICHIER_SAUVERALBUM         -25324
#define IDM_SITEWEB                     40213
#define ID_IMAGE_AUTODIMENSIONNEMENT    40214
#define ID_IMAGE_REINIT                 40215
#define ID_PICTURE_AUTOSIZE             40216
#define ID_IMAGEN_TAMANOAUTOMATICO      40217
#define ID_VID40218                     40218
#define ID_VIDEXTRACTPICTURE            40219
#define ID_IMAGES_AFFICHERINFOS         40220
#define ID_AJUSTEMENT_PHOTOFILTRE       40225
#define ID_MODE_SEPIA                   40226
#define ID_AJUSTEMENT_NIVEAU            40227
#define ID_IMAGE_AFFICHAGEHISTOGRAMME   40228
#define ID_IMAGE_INFOS                  40230
#define ID_IMAGE_AFFICHERLESINFOSIMAGES 40231
#define ID_IMAGE_AFFICHERL              40232
#define IDM_RETOURWINDOW                40236
#define ID_VISUALISATION_RETOURFEN40238 40238
#define ID_VISUALIZACION_VENTANA        40239
#define ID_AFFICHAGE_SAUVERLESMINIATURES 40240
#define ID_VIEW_SAVETHUMBNAIL           40241
#define ID_VISUALIZACI40242             40242
#define ID_DIAPORAMA_EN3D               40243
#define ID_OPTIONS_ACC40244             40244
#define ID_OPTIONS_GPGPU                40245
#define ID_STTEXTAUTEUR                 65535
#define ID_STTEXTCOPYRIGHT              65535
#define IDC_STTRAITEMENT                -1

#define ID_FILE_NEW						40246
#define ID_FILE_OPEN					40247
#define ID_FILE_SAVE					40248
#define ID_EDIT_CUT						40249
#define ID_EDIT_COPY					40250	
#define ID_EDIT_PASTE					40251
#define ID_FILE_PRINT					40252
#define ID_APP_ABOUT					40253

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         40246
#define _APS_NEXT_CONTROL_VALUE         1302
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
